import type { AccessMethod, SupplierAdapter } from "../../types";
import { DemoSupplierAdapter, type DemoSupplierProfile } from "./demo-adapter";

/**
 * DEMO SUPPLIERS — fictional stores with generated prices. They exist so the
 * whole platform runs end to end before real integrations are connected.
 * Replace them one by one with real adapters in ../ (see docs/ARCHITECTURE.md).
 */
const DEMO_ACCESS: AccessMethod = {
  kind: "demo",
  summary: "Generated sample prices; no real store is contacted.",
  steps: ["Compute a deterministic price from (store, product, day)."],
  entryPoints: [],
  fields: {},
  robots: { checkedOn: "n/a", notes: "Not applicable." },
  politeness: { delayMs: 0, maxRequestsPerRun: 0 },
  liveSearch: { supported: true },
};

const PROFILES: DemoSupplierProfile[] = [
  {
    definition: {
      id: "texnobaku",
      name: "TexnoBaku",
      scope: "local",
      originCountry: "AZ",
      currency: "AZN",
      websiteUrl: "https://texnobaku.example",
      trustScore: 88,
      integration: "demo",
      access: DEMO_ACCESS,
      categories: ["electronics"],
    },
    priceLevel: 1.2,
    coverage: 0.9,
    promoRate: 0.3,
    shipping: 0,
    deliveryDays: { min: 1, max: 2 },
    publishesGtin: false,
    inflatesListPrice: false,
    titleStyle: "brand-first",
    latencyMs: [350, 900],
  },
  {
    definition: {
      id: "elektromart",
      name: "Elektro Mart",
      scope: "local",
      originCountry: "AZ",
      currency: "AZN",
      websiteUrl: "https://elektromart.example",
      trustScore: 80,
      integration: "demo",
      access: DEMO_ACCESS,
      categories: ["electronics", "toys"],
    },
    priceLevel: 1.24,
    coverage: 0.7,
    promoRate: 0.26,
    shipping: 5,
    deliveryDays: { min: 1, max: 3 },
    publishesGtin: true,
    inflatesListPrice: true,
    titleStyle: "brand-first",
    latencyMs: [500, 1400],
  },
  {
    definition: {
      id: "gozellik-evi",
      name: "Gözəllik Evi",
      scope: "local",
      originCountry: "AZ",
      currency: "AZN",
      websiteUrl: "https://gozellikevi.example",
      trustScore: 85,
      integration: "demo",
      access: DEMO_ACCESS,
      categories: ["beauty"],
    },
    priceLevel: 1.28,
    coverage: 0.9,
    promoRate: 0.34,
    shipping: 3,
    deliveryDays: { min: 1, max: 2 },
    publishesGtin: true,
    inflatesListPrice: false,
    titleStyle: "brand-first",
    latencyMs: [400, 1100],
  },
  {
    definition: {
      id: "oyuncaq-dunyasi",
      name: "Oyuncaq Dünyası",
      scope: "local",
      originCountry: "AZ",
      currency: "AZN",
      websiteUrl: "https://oyuncaqdunyasi.example",
      trustScore: 82,
      integration: "demo",
      access: DEMO_ACCESS,
      categories: ["toys"],
    },
    priceLevel: 1.3,
    coverage: 0.85,
    promoRate: 0.3,
    shipping: 4,
    deliveryDays: { min: 1, max: 3 },
    publishesGtin: true,
    inflatesListPrice: false,
    titleStyle: "model-first",
    latencyMs: [600, 1500],
  },
  {
    definition: {
      id: "globalmart",
      name: "GlobalMart",
      scope: "global",
      originCountry: "US",
      currency: "USD",
      websiteUrl: "https://globalmart.example",
      trustScore: 92,
      integration: "demo",
      access: DEMO_ACCESS,
      categories: ["electronics", "beauty", "toys"],
    },
    priceLevel: 1,
    coverage: 0.85,
    promoRate: 0.3,
    shipping: null,
    publishesGtin: true,
    inflatesListPrice: false,
    titleStyle: "brand-first",
    latencyMs: [900, 2200],
  },
  {
    definition: {
      id: "euroshop",
      name: "EuroShop",
      scope: "global",
      originCountry: "DE",
      currency: "EUR",
      websiteUrl: "https://euroshop.example",
      trustScore: 86,
      integration: "demo",
      access: DEMO_ACCESS,
      categories: ["electronics", "beauty", "toys"],
    },
    priceLevel: 1.06,
    coverage: 0.6,
    promoRate: 0.28,
    shipping: 12,
    deliveryDays: { min: 6, max: 10 },
    publishesGtin: true,
    inflatesListPrice: false,
    titleStyle: "model-first",
    latencyMs: [1200, 2600],
  },
  {
    definition: {
      id: "anadolu-market",
      name: "Anadolu Market",
      scope: "global",
      originCountry: "TR",
      currency: "TRY",
      websiteUrl: "https://anadolumarket.example",
      trustScore: 78,
      integration: "demo",
      access: DEMO_ACCESS,
      categories: ["beauty", "toys", "electronics"],
    },
    priceLevel: 1.03,
    coverage: 0.55,
    promoRate: 0.34,
    shipping: null,
    publishesGtin: true,
    inflatesListPrice: true,
    titleStyle: "brand-first",
    latencyMs: [700, 1800],
  },
  {
    definition: {
      id: "asiadirect",
      name: "AsiaDirect",
      scope: "global",
      originCountry: "CN",
      currency: "USD",
      websiteUrl: "https://asiadirect.example",
      trustScore: 70,
      integration: "demo",
      access: DEMO_ACCESS,
      categories: ["electronics", "toys"],
    },
    priceLevel: 0.93,
    coverage: 0.4,
    promoRate: 0.3,
    shipping: 6,
    deliveryDays: { min: 14, max: 25 },
    publishesGtin: false,
    inflatesListPrice: false,
    titleStyle: "brand-first",
    latencyMs: [1500, 3000],
  },
];

export const demoAdapters: SupplierAdapter[] = PROFILES.map(
  (profile) => new DemoSupplierAdapter(profile),
);
