import type { StructuredDataStore } from "./adapter";

/**
 * Stores read through their sitemap + schema.org product data, checked on
 * 2026-10-01 (`npm run store:probe -- <host>` checks a new one). Turkey
 * first: it is where most people in Azerbaijan order clothing, shoes and
 * cosmetics from (forwarders deliver in under a week).
 *
 * Same rule as every other store: only a brand's own official store or a
 * long-established retailer. Big brands that refuse automated visitors (Zara,
 * Koton, LC Waikiki, DeFacto, Lumberjack/FLO, Mango, Lacoste…) are listed in
 * docs/SUPPLIERS.md, not worked around.
 */

/** Brands people in Azerbaijan look for most, as they appear in URL slugs. */
const POPULAR_SPORT = /adidas|puma|nike|jordan|new-balance|skechers|converse|vans|reebok|asics|lumberjack|columbia|timberland|crocs/;
const POPULAR_FASHION = /lacoste|tommy|calvin-klein|guess|michael-kors|hugo|boss|armani|ralph-lauren|gant|karl-lagerfeld|diesel|levi/;
const POPULAR_BEAUTY = /loreal|l-oreal|maybelline|nivea|garnier|la-roche|cerave|vichy|nyx|essence|flormar|golden-rose|pastel|bioderma|the-purest|neutrogena|avene|clinique|estee|mac-|dior|chanel/;
/** Gratis's own brands, sold nowhere else online, read before the rest of Gratis. */
const GRATIS_OWN_BRANDS = /\/(bee-beauty|beaulis|lykd|benri)-/;
const POPULAR_WATCHES = /\/(casio|g-shock|tissot|seiko|citizen|lacoste|tommy-hilfiger|guess|michael-kors|daniel-wellington|swatch|fossil|armani|hugo-boss|boss|police|orient)-/;

export const STRUCTURED_DATA_STORES: StructuredDataStore[] = [
  {
    id: "superstep",
    name: "SuperStep",
    origin: "https://www.superstep.com.tr",
    originCountry: "TR",
    currency: "TRY",
    reliability: { basis: "established-retailer", note: "One of Turkey's largest sneaker and sportswear chains, selling adidas, Nike, Puma, New Balance and others" },
    shipsToMarket: false,
    categories: ["shoes", "bags", "fashion"],
    sitemap: "https://www.superstep.com.tr/sitemap.xml",
    productSitemaps: /\/sitemap\/products-/,
    productUrl: /\/urun\//,
    focus: POPULAR_SPORT,
    listPrice: "retail-price",
  },
  {
    id: "sneaksup",
    name: "Sneaks Up",
    origin: "https://www.sneaksup.com",
    originCountry: "TR",
    currency: "TRY",
    reliability: { basis: "established-retailer", note: "Turkish multi-brand sneaker and streetwear retailer with stores in major cities" },
    shipsToMarket: false,
    categories: ["shoes", "bags", "fashion"],
    sitemap: "https://www.sneaksup.com/sitemap.xml",
    productSitemaps: /type=Products/,
    productUrl: /-p-\d+$/,
    focus: POPULAR_SPORT,
    listPrice: "old-price-json",
  },
  {
    id: "intersport-tr",
    name: "Intersport Türkiye",
    origin: "https://www.intersport.com.tr",
    originCountry: "TR",
    currency: "TRY",
    reliability: { basis: "established-retailer", note: "Turkish arm of Intersport, the international sporting-goods chain" },
    shipsToMarket: false,
    categories: ["shoes", "bags", "fashion", "sports"],
    sitemap: "https://www.intersport.com.tr/sitemap.xml",
    productSitemaps: /sitemap-products-/,
    productUrl: /\/urun\//,
    focus: POPULAR_SPORT,
    listPrice: "ga4-discount",
  },
  {
    id: "barcin",
    name: "Barçın",
    origin: "https://www.barcin.com",
    originCountry: "TR",
    currency: "TRY",
    reliability: { basis: "established-retailer", note: "Long-established Turkish sneaker and sportswear chain" },
    shipsToMarket: false,
    categories: ["shoes", "bags", "fashion", "sports"],
    sitemap: "https://www.barcin.com/sitemap.xml",
    productSitemaps: /\/sitemap\/products-/,
    productUrl: /^https:\/\/www\.barcin\.com\/[^/?]+\/$/,
    focus: POPULAR_SPORT,
    listPrice: "retail-price",
  },
  {
    id: "beymen",
    name: "Beymen",
    origin: "https://www.beymen.com",
    originCountry: "TR",
    currency: "TRY",
    reliability: { basis: "established-retailer", note: "Turkey's best-known luxury department store, selling designer brands since 1971" },
    shipsToMarket: false,
    categories: ["shoes", "bags", "watches", "jewelry", "home", "fashion"],
    sitemap: "https://www.beymen.com/sitemap.xml",
    productSitemaps: /\/tr\/product_\d+\.xml$/,
    productUrl: /\/tr\/p_/,
    focus: POPULAR_FASHION,
    listPrice: "old-price-field",
  },
  {
    id: "network",
    name: "Network",
    origin: "https://www.network.com.tr",
    originCountry: "TR",
    currency: "TRY",
    reliability: { basis: "official-brand-store", note: "Official online store of the Turkish fashion brand Network" },
    shipsToMarket: false,
    categories: ["shoes", "bags", "fashion"],
    fallbackCategory: "fashion",
    sitemap: "https://www.network.com.tr/sitemap.xml",
    productSitemaps: /\/product_\d+\.xml$/,
    productUrl: /-p-\d+$/,
    brand: "Network",
  },
  {
    id: "colins",
    name: "Colin's",
    origin: "https://www.colins.com.tr",
    originCountry: "TR",
    currency: "TRY",
    reliability: { basis: "official-brand-store", note: "Official online store of the Turkish denim and casual-wear brand Colin's" },
    shipsToMarket: false,
    categories: ["shoes", "bags", "fashion"],
    fallbackCategory: "fashion",
    sitemap: "https://www.colins.com.tr/Sitemap",
    productSitemaps: /SitemapProducts/,
    productUrl: /\/p\//,
    brand: "Colin's",
    listPrice: "ga4-discount",
  },
  {
    id: "damattween",
    name: "Damat Tween",
    origin: "https://www.damattween.com",
    originCountry: "TR",
    currency: "TRY",
    reliability: { basis: "official-brand-store", note: "Official online store of the Turkish menswear brands Damat and Tween" },
    shipsToMarket: false,
    categories: ["shoes", "bags", "fashion"],
    fallbackCategory: "fashion",
    sitemap: "https://www.damattween.com/sitemap.xml",
    productSitemaps: /sitemap-products-/,
    productUrl: /-\d{8,14}\/$/,
    listPrice: "retail-price",
  },
  {
    id: "altinyildiz",
    name: "Altınyıldız Classics",
    origin: "https://www.altinyildizclassics.com",
    originCountry: "TR",
    currency: "TRY",
    reliability: { basis: "official-brand-store", note: "Official online store of the Turkish menswear brand Altınyıldız Classics" },
    shipsToMarket: false,
    categories: ["shoes", "bags", "fashion"],
    fallbackCategory: "fashion",
    sitemap: "https://www.altinyildizclassics.com/sitemap.xml",
    productSitemaps: /sitemap_products/,
    productUrl: /-p$/,
    brand: "Altınyıldız Classics",
    listPrice: "ga4-discount",
  },
  {
    id: "saatvesaat",
    name: "Saat&Saat",
    origin: "https://www.saatvesaat.com.tr",
    originCountry: "TR",
    currency: "TRY",
    reliability: { basis: "established-retailer", note: "Turkey's largest watch retailer, authorised dealer of Tissot, Seiko, Casio and other brands" },
    shipsToMarket: false,
    categories: ["watches", "jewelry", "bags"],
    sitemap: "https://www.saatvesaat.com.tr/media/sitemap.xml",
    productSitemaps: /product_sitemap/,
    productUrl: /-p-[a-z0-9]+$/,
    focus: POPULAR_WATCHES,
    listPrice: "ga4-discount",
  },
  {
    id: "atasay",
    name: "Atasay",
    origin: "https://www.atasay.com",
    originCountry: "TR",
    currency: "TRY",
    reliability: { basis: "official-brand-store", note: "Official online store of Atasay, one of Turkey's largest jewelers (since 1987)" },
    shipsToMarket: false,
    categories: ["watches", "jewelry"],
    fallbackCategory: "jewelry",
    sitemap: "https://www.atasay.com/sitemap.xml",
    productSitemaps: /sitemap-products-/,
    productUrl: /\/tr\//,
    brand: "Atasay",
    listPrice: "retail-price",
  },
  {
    id: "altinbas",
    name: "Altınbaş",
    origin: "https://www.altinbas.com",
    originCountry: "TR",
    currency: "TRY",
    reliability: { basis: "official-brand-store", note: "Official online store of Altınbaş, one of Turkey's largest jewelers" },
    shipsToMarket: false,
    categories: ["watches", "jewelry"],
    fallbackCategory: "jewelry",
    sitemap: "https://www.altinbas.com/sitemap.xml",
    productUrl: /\/urun\//,
    brand: "Altınbaş",
    listPrice: "ga4-discount",
  },
  {
    id: "pierrecardin-tr",
    name: "Pierre Cardin Türkiye",
    origin: "https://www.pierrecardin.com.tr",
    originCountry: "TR",
    currency: "TRY",
    reliability: { basis: "official-brand-store", note: "Official Turkish online store of Pierre Cardin" },
    shipsToMarket: false,
    categories: ["shoes", "bags", "watches", "fashion"],
    fallbackCategory: "fashion",
    sitemap: "https://www.pierrecardin.com.tr/sitemap.xml",
    productSitemaps: /\/sitemap\/products-/,
    productUrl: /^https:\/\/www\.pierrecardin\.com\.tr\/[^/?]+\/$/,
    brand: "Pierre Cardin",
    listPrice: "retail-price",
  },
  {
    id: "mudo",
    name: "Mudo",
    origin: "https://www.mudo.com.tr",
    originCountry: "TR",
    currency: "TRY",
    reliability: { basis: "official-brand-store", note: "Official online store of the Turkish fashion and lifestyle brand Mudo" },
    shipsToMarket: false,
    categories: ["shoes", "bags", "jewelry", "fashion"],
    sitemap: "https://www.mudo.com.tr/sitemap.xml",
    productSitemaps: /sitemap-products-/,
    productUrl: /^https:\/\/www\.mudo\.com\.tr\/[^/?]+\/$/,
    brand: "Mudo",
    listPrice: "retail-price",
  },
  {
    id: "ozdilek",
    name: "Özdilekteyim",
    origin: "https://www.ozdilekteyim.com",
    originCountry: "TR",
    currency: "TRY",
    reliability: { basis: "established-retailer", note: "Online store of Özdilek, a Turkish department-store chain" },
    shipsToMarket: false,
    categories: ["shoes", "bags", "watches", "jewelry", "home", "baby", "fashion", "sports"],
    sitemap: "https://www.ozdilekteyim.com/medias2/sitemap.xml",
    productSitemaps: /product-tr-try-\d+\.xml$/,
    productUrl: /-p-\d+$/,
    focus: new RegExp(`${POPULAR_SPORT.source}|${POPULAR_FASHION.source}|pierre-cardin|us-polo`),
  },
  // Beauty
  {
    id: "gratis",
    name: "Gratis",
    origin: "https://www.gratis.com",
    originCountry: "TR",
    currency: "TRY",
    reliability: { basis: "established-retailer", note: "Turkey's largest personal-care and cosmetics chain" },
    shipsToMarket: false,
    categories: ["beauty"],
    sitemap: "https://www.gratis.com/sitemap.xml",
    productSitemaps: /Product-tr-TRY/,
    productUrl: /-p-\d+$/,
    focus: new RegExp(`${GRATIS_OWN_BRANDS.source}|${POPULAR_BEAUTY.source}`),
    // Its own brands alone are ~1,400 products; 900 pages take ~23 min at one every 1.5 s.
    productsPerRun: 900,
  },
  {
    id: "pastel",
    name: "Pastel",
    origin: "https://www.pastelshop.com",
    originCountry: "TR",
    currency: "TRY",
    reliability: { basis: "official-brand-store", note: "Official online store of the Turkish cosmetics brand Pastel (Pastel, Show by Pastel)" },
    shipsToMarket: false,
    categories: ["beauty"],
    fallbackCategory: "beauty",
    sitemap: "https://www.pastelshop.com/xml/sitemap/sitemap.xml",
    productSitemaps: /\/product\.xml$/,
    productUrl: /^https:\/\/www\.pastelshop\.com\/[^/?#]+$/,
    // The whole catalog (~880 products): ~22 min at one page every 1.5 s.
    productsPerRun: 900,
  },
  {
    id: "sinoz",
    name: "Sinoz",
    origin: "https://www.sinoz.com.tr",
    originCountry: "TR",
    currency: "TRY",
    reliability: { basis: "official-brand-store", note: "Official online store of the Turkish skin-care brand Sinoz" },
    shipsToMarket: false,
    categories: ["beauty"],
    fallbackCategory: "beauty",
    sitemap: "https://www.sinoz.com.tr/sitemap.xml",
    productUrl: /-p$/,
    brand: "Sinoz",
  },
  {
    id: "rossmann-tr",
    name: "Rossmann Türkiye",
    origin: "https://www.rossmann.com.tr",
    originCountry: "TR",
    currency: "TRY",
    reliability: { basis: "established-retailer", note: "Turkish arm of Rossmann, the German drugstore chain" },
    shipsToMarket: false,
    categories: ["beauty"],
    sitemap: "https://www.rossmann.com.tr/media/sitemap/sitemap.xml",
    productUrl: /-p-[a-z0-9]+$/,
    focus: POPULAR_BEAUTY,
  },
  {
    id: "flormar",
    name: "Flormar",
    origin: "https://www.flormar.com.tr",
    originCountry: "TR",
    currency: "TRY",
    reliability: { basis: "official-brand-store", note: "Official online store of the Turkish cosmetics brand Flormar" },
    shipsToMarket: false,
    categories: ["beauty"],
    fallbackCategory: "beauty",
    sitemap: "https://www.flormar.com.tr/sitemap.xml",
    productSitemaps: /sitemap-products-/,
    productUrl: /\/$/,
    brand: "Flormar",
    listPrice: "retail-price",
  },
  // Turkish brands added 2026-10-09 (clothing, shoes, bags)
  {
    id: "desa",
    name: "Desa",
    origin: "https://www.desa.com.tr",
    originCountry: "TR",
    currency: "TRY",
    reliability: { basis: "official-brand-store", note: "Official online store of the Turkish leather brand Desa (bags, shoes, leather clothing)" },
    shipsToMarket: false,
    categories: ["bags", "shoes", "fashion"],
    sitemap: "https://www.desa.com.tr/sitemap.xml",
    productSitemaps: /\/sitemap\/products\/\d+\.xml$/,
    productUrl: /-\d+$/,
    brand: "Desa",
  },
  {
    id: "sarar",
    name: "Sarar",
    origin: "https://sarar.com",
    originCountry: "TR",
    currency: "TRY",
    reliability: { basis: "official-brand-store", note: "Official online store of the Turkish fashion house Sarar (Sarar, Interview)" },
    shipsToMarket: false,
    categories: ["fashion", "shoes", "bags", "home"],
    sitemap: "https://sarar.com/xml/sitemap/sitemap.xml",
    productSitemaps: /\/product\.xml$/,
    productUrl: /-\d+$/,
    // Clothing first: the newest pages are mostly Sarar Home bedding.
    focus: /gomlek|ceket|pantolon|elbise|takim|kazak|tisort|t-shirt|sweatshirt|mont|kaban|etek|bluz|hirka|yelek|ayakkabi|canta/,
  },
  {
    id: "roman",
    name: "Roman",
    origin: "https://roman.com.tr",
    originCountry: "TR",
    currency: "TRY",
    reliability: { basis: "official-brand-store", note: "Official online store of the Turkish womenswear brand Roman" },
    shipsToMarket: false,
    categories: ["fashion", "shoes", "bags", "jewelry"],
    sitemap: "https://www.roman.com.tr/xml/sitemap/sitemap.xml",
    productSitemaps: /\/product\.xml$/,
    productUrl: /^https:\/\/roman\.com\.tr\/[^?#]+$/,
    brand: "Roman",
  },
  {
    id: "tergan",
    name: "Tergan",
    origin: "https://www.tergan.com.tr",
    originCountry: "TR",
    currency: "TRY",
    reliability: { basis: "official-brand-store", note: "Official online store of the Turkish leather shoe and bag brand Tergan" },
    shipsToMarket: false,
    categories: ["shoes", "bags", "fashion"],
    sitemap: "https://www.tergan.com.tr/xml/sitemap/sitemap.xml",
    productSitemaps: /\/product\.xml$/,
    productUrl: /^https:\/\/www\.tergan\.com\.tr\/[^/?#]+$/,
    brand: "Tergan",
  },
  {
    id: "divarese",
    name: "Divarese",
    origin: "https://www.divarese.com.tr",
    originCountry: "TR",
    currency: "TRY",
    reliability: { basis: "official-brand-store", note: "Official online store of the Turkish shoe and bag brand Divarese (also its sister brand George Hogg)" },
    shipsToMarket: false,
    categories: ["shoes", "bags", "fashion"],
    sitemap: "https://www.divarese.com.tr/sitemap.xml",
    productSitemaps: /\/product_\d+\.xml$/,
    productUrl: /-p-\d+$/,
  },
  {
    id: "procsin",
    name: "Procsin",
    origin: "https://www.procsin.com",
    originCountry: "TR",
    currency: "TRY",
    reliability: { basis: "official-brand-store", note: "Official online store of the Turkish skin and hair care brand Procsin" },
    shipsToMarket: false,
    categories: ["beauty"],
    fallbackCategory: "beauty",
    sitemap: "https://www.procsin.com/sitemap.xml",
    productUrl: /\/product\//,
    brand: "Procsin",
  },
  {
    id: "siveno",
    name: "Siveno",
    origin: "https://siveno.com",
    originCountry: "TR",
    currency: "TRY",
    reliability: { basis: "official-brand-store", note: "Official online store of the Turkish natural soap and care brand Siveno" },
    shipsToMarket: false,
    categories: ["beauty"],
    fallbackCategory: "beauty",
    sitemap: "https://siveno.com/sitemap.xml",
    productUrl: /\/urun\//,
    brand: "Siveno",
  },
  // Toys
  {
    id: "pilsan",
    name: "Pilsan",
    origin: "https://www.pilsanstore.com.tr",
    originCountry: "TR",
    currency: "TRY",
    reliability: { basis: "official-brand-store", note: "Official online store of the Turkish toy maker Pilsan (ride-ons, play sets, outdoor toys)" },
    shipsToMarket: false,
    categories: ["toys"],
    fallbackCategory: "toys",
    sitemap: "https://www.pilsanstore.com.tr/sitemap.xml",
    productSitemaps: /sitemap_product_\d+\.xml/,
    productUrl: /\/urun\//,
    brand: "Pilsan",
    listPrice: "strikethrough",
  },
  // Electronics
  {
    id: "troy",
    name: "Troy",
    origin: "https://www.troyestore.com",
    originCountry: "TR",
    currency: "TRY",
    reliability: { basis: "established-retailer", note: "Apple Premium Partner in Turkey, with stores in major cities" },
    shipsToMarket: false,
    categories: ["electronics"],
    fallbackCategory: "electronics",
    sitemap: "https://www.troyestore.com/sitemap.xml",
    productSitemaps: /sitemap-product/,
    productUrl: /_\d+$/,
    focus: /iphone|ipad|macbook|airpods|apple-watch|imac|mac-mini/,
    brandFromTitle: true,
    listPrice: "ga4-discount",
  },
  {
    id: "gaming-gen-tr",
    name: "Gaming.gen.tr",
    origin: "https://www.gaming.gen.tr",
    originCountry: "TR",
    currency: "TRY",
    reliability: { basis: "established-retailer", note: "Long-running Turkish retailer of gaming PCs, components and peripherals" },
    shipsToMarket: false,
    categories: ["electronics"],
    fallbackCategory: "electronics",
    sitemap: "https://www.gaming.gen.tr/wp-sitemap.xml",
    productSitemaps: /wp-sitemap-posts-product-\d+/,
    productUrl: /\/urun\/\d+\//,
  },
  // Toys
  {
    id: "armagan-oyuncak",
    name: "Armağan Oyuncak",
    origin: "https://www.armaganoyuncak.com.tr",
    originCountry: "TR",
    currency: "TRY",
    reliability: { basis: "established-retailer", note: "Long-established Turkish toy-store chain" },
    shipsToMarket: false,
    categories: ["toys"],
    fallbackCategory: "toys",
    sitemap: "https://www.armaganoyuncak.com.tr/pub/media/sitemap.xml",
    productSitemaps: /product_sitemap/,
    productUrl: /-p-[a-z0-9]+$/,
    focus: /lego|barbie|hot-wheels|playmobil|nerf|disney|marvel|fisher-price|monster-high/,
  },
  // Home & kitchen
  {
    id: "bernardo",
    name: "Bernardo",
    origin: "https://www.bernardo.com.tr",
    originCountry: "TR",
    currency: "TRY",
    reliability: { basis: "official-brand-store", note: "Official online store of the Turkish kitchenware brand Bernardo" },
    shipsToMarket: false,
    categories: ["home"],
    fallbackCategory: "home",
    sitemap: "https://www.bernardo.com.tr/sitemap.xml",
    productSitemaps: /sitemap_product_\d+\.xml/,
    productUrl: /\/urun\//,
    brand: "Bernardo",
    listPrice: "strikethrough",
  },
  {
    id: "emsan",
    name: "Emsan",
    origin: "https://www.emsan.com.tr",
    originCountry: "TR",
    currency: "TRY",
    reliability: { basis: "official-brand-store", note: "Official online store of the Turkish tableware and cookware brand Emsan" },
    shipsToMarket: false,
    categories: ["home"],
    fallbackCategory: "home",
    sitemap: "https://www.emsan.com.tr/sitemap.xml",
    productSitemaps: /category-product\d+\.xml$/,
    productUrl: /\/urun\//,
    brand: "Emsan",
  },
  {
    id: "karaca",
    name: "Karaca",
    origin: "https://www.karaca.com",
    originCountry: "TR",
    currency: "TRY",
    reliability: { basis: "established-retailer", note: "Large Turkish kitchenware and home retailer, also selling Alessi, WMF and other brands" },
    shipsToMarket: false,
    categories: ["home"],
    sitemap: "https://www.karaca.com/sitemap.xml",
    productSitemaps: /category-product\d+\.xml$/,
    productUrl: /\/urun\//,
    focus: /kahve|espresso|blender|airfryer|air-fryer|fritoz|tost|kettle|supurge|tencere|tava|bicak/,
  },
  {
    id: "fakir",
    name: "Fakir",
    origin: "https://www.fakir.com.tr",
    originCountry: "TR",
    currency: "TRY",
    reliability: { basis: "official-brand-store", note: "Official online store of the Turkish appliance brand Fakir" },
    shipsToMarket: false,
    categories: ["home"],
    fallbackCategory: "home",
    sitemap: "https://www.fakir.com.tr/xml/sitemap/sitemap.xml",
    productSitemaps: /\/product\.xml$/,
    productUrl: /^https:\/\/www\.fakir\.com\.tr\/[^/?]+$/,
    brand: "Fakir",
  },
  {
    id: "tefal-tr",
    name: "Tefal Türkiye",
    origin: "https://www.tefal.com.tr",
    originCountry: "TR",
    currency: "TRY",
    reliability: { basis: "official-brand-store", note: "Official Turkish store of Groupe SEB: Tefal, Rowenta, Moulinex and Krups" },
    shipsToMarket: false,
    categories: ["home"],
    fallbackCategory: "home",
    sitemap: "https://www.tefal.com.tr/sitemap.xml",
    productSitemaps: /sitemap-products-/,
    productUrl: /\/$/,
    brandFromTitle: true,
    listPrice: "retail-price",
  },
  // Sports & outdoor
  {
    id: "spx",
    name: "SPX",
    origin: "https://www.spx.com.tr",
    originCountry: "TR",
    currency: "TRY",
    reliability: { basis: "established-retailer", note: "Turkish outdoor and action-sports retailer: Salomon, The North Face, Stanley, Quiksilver and others" },
    shipsToMarket: false,
    categories: ["shoes", "bags", "fashion", "sports"],
    sitemap: "https://www.spx.com.tr/sitemap.xml",
    productSitemaps: /sitemap-products-/,
    productUrl: /^https:\/\/www\.spx\.com\.tr\/[^/?]+\/$/,
    focus: /salomon|the-north-face|columbia|stanley|merrell|helly|jack-wolfskin|thule|osprey|quiksilver/,
    listPrice: "retail-price",
  },
];
